-- ============================================================
-- STREAMER HUB - SUPABASE SECURE PRODUCTION SETUP
-- Ejecutar UNA SOLA VEZ en Supabase > SQL Editor.
-- Después crea tu usuario administrador en Authentication > Users
-- y añade ese usuario a public.admins con el bloque final.
-- ============================================================

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.site_config (
  id integer primary key,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_revisions (
  id bigint generated by default as identity primary key,
  config jsonb not null,
  created_at timestamptz not null default now()
);

insert into public.site_config (id, config)
values (1, '{}'::jsonb)
on conflict (id) do nothing;

-- Privilegios mínimos explícitos
revoke all on table public.admins from anon, authenticated;
revoke all on table public.site_config from anon, authenticated;
revoke all on table public.site_revisions from anon, authenticated;

grant select on table public.admins to authenticated;
grant select on table public.site_config to anon, authenticated;
grant update on table public.site_config to authenticated;
grant select, insert on table public.site_revisions to authenticated;

do $$
begin
  if exists (
    select 1 from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname='public' and c.relname='site_revisions_id_seq'
  ) then
    grant usage, select on sequence public.site_revisions_id_seq to authenticated;
  end if;
end $$;

alter table public.admins enable row level security;
alter table public.site_config enable row level security;
alter table public.site_revisions enable row level security;

-- Un usuario autenticado solo puede comprobar SU propia fila de admin.
drop policy if exists "Admin can read own admin row" on public.admins;
create policy "Admin can read own admin row"
on public.admins
for select
to authenticated
using (user_id = auth.uid());

-- El sitio público puede leer SOLO la configuración publicada.
drop policy if exists "Public can read site config" on public.site_config;
create policy "Public can read site config"
on public.site_config
for select
to anon, authenticated
using (id = 1);

-- Solo un UUID incluido en public.admins puede publicar.
drop policy if exists "Only admins can update site config" on public.site_config;
create policy "Only admins can update site config"
on public.site_config
for update
to authenticated
using (
  id = 1 and exists (
    select 1 from public.admins a where a.user_id = auth.uid()
  )
)
with check (
  id = 1 and exists (
    select 1 from public.admins a where a.user_id = auth.uid()
  )
);

-- Historial privado: solo administradores.
drop policy if exists "Admins can read revisions" on public.site_revisions;
create policy "Admins can read revisions"
on public.site_revisions
for select
to authenticated
using (
  exists (select 1 from public.admins a where a.user_id = auth.uid())
);

drop policy if exists "Admins can insert revisions" on public.site_revisions;
create policy "Admins can insert revisions"
on public.site_revisions
for insert
to authenticated
with check (
  exists (select 1 from public.admins a where a.user_id = auth.uid())
);

-- Bucket público únicamente para MOSTRAR imágenes del sitio.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  6291456,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Lectura pública de imágenes.
drop policy if exists "Public can view site media" on storage.objects;
create policy "Public can view site media"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'site-media');

-- Escritura: solo admin y solo dentro de su carpeta UUID/...
drop policy if exists "Admins can upload site media" on storage.objects;
create policy "Admins can upload site media"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'site-media'
  and (storage.foldername(name))[1] = auth.uid()::text
  and exists (select 1 from public.admins a where a.user_id = auth.uid())
);

drop policy if exists "Admins can update site media" on storage.objects;
create policy "Admins can update site media"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'site-media'
  and (storage.foldername(name))[1] = auth.uid()::text
  and exists (select 1 from public.admins a where a.user_id = auth.uid())
)
with check (
  bucket_id = 'site-media'
  and (storage.foldername(name))[1] = auth.uid()::text
  and exists (select 1 from public.admins a where a.user_id = auth.uid())
);

drop policy if exists "Admins can delete site media" on storage.objects;
create policy "Admins can delete site media"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'site-media'
  and (storage.foldername(name))[1] = auth.uid()::text
  and exists (select 1 from public.admins a where a.user_id = auth.uid())
);

-- ============================================================
-- AÑADIR EL PRIMER ADMINISTRADOR
-- ============================================================
-- OPCIÓN A (más fácil): reemplaza el correo por el usuario que creaste
-- en Authentication > Users y ejecuta SOLO este INSERT:
--
-- insert into public.admins(user_id)
-- select id from auth.users
-- where lower(email) = lower('TU_CORREO@EJEMPLO.COM')
-- on conflict (user_id) do nothing;
--
-- OPCIÓN B: si ya copiaste el UUID:
-- insert into public.admins(user_id)
-- values ('PASTE_YOUR_AUTH_USER_UUID_HERE')
-- on conflict (user_id) do nothing;
